version: "3.9"
services:
  redis:
    image: redis:7-alpine
    command: ["redis-server",
              "--appendonly", "yes",
              "--appendfsync", "everysec",
              "--notify-keyspace-events", "KEA"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  redis_exporter:
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - redis_exporter

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
    depends_on:
      - prometheus

  locust:
    image: locustio/locust:latest
    depends_on:
      - backend
    volumes:
      - ./loadtest/locustfile.py:/mnt/locust/locustfile.py:ro
      - ./loadtest/testdata.jsonl:/mnt/locust/testdata.jsonl:ro
    working_dir: /mnt/locust
    command: >
      -f locustfile.py
      --headless
      -u 300
      -r 300
      --host http://backend:3000


volumes:
  redis-data:
